### ISSUE TITLE
Add openvpn-as service

### ISSUE THREAD

**Issue by TheHackmeister** [SciFiFarms/TechnoCore#36]
It would be helpful to have an OpenVPN service so that people can securely manage their home while they are away. 

The [openvpn-as image](https://hub.docker.com/r/linuxserver/openvpn-as/) looks to be the easiest to use. By that I mean it has a GUI. However, it tries to modify network settings, and thus needs to be ran as net-admin. I'd rather figure out how to not require that. Alternatively, we could set up a wrapper similarly to [TechnoCore-esphomeyaml-Wrapper](https://github.com/SciFiFarms/TechnoCore-esphomeyaml-Wrapper). 

I've already sketched in the OpenVPN service, but because of the net-admin requirement, it doesn't work:
```
    openvpn:
    deploy:
      mode: global
      restart_policy:
        condition: any
    image: linuxserver/openvpn-as 
    networks:
      - web
    ports:
      - "943:943"
    #volumes:
    #  - openvpn:/data
```
